<?php

namespace Database\Factories;

use App\Models\{Transaction, Store, Product, User};
use Illuminate\Database\Eloquent\Factories\Factory;

class TransactionFactory extends Factory
{
    protected $model = Transaction::class;

    public function definition(): array
    {
        $cost = $this->faker->randomFloat(2, 100, 5000);
        $quantity = $this->faker->numberBetween(1, 10);

        return [
            'store_id' => Store::factory(),
            'product_id' => Product::factory(),
            'buyer_id' => User::factory(),
            'cost' => $cost,
            'quantity' => $quantity,
            // total is generated by DB, but we can set it too
            'total' => $cost * $quantity,
            'time' => $this->faker->dateTimeThisYear(),
        ];
    }
}
